name: Test Selenium UI Automation Workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Running Test Selenium UI Automation Framework with Maven
      env:
        LT_USERNAME: ${{ secrets.LT_USERNAME }}
        LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
      run: mvn test -X -Dbrowsername=chrome -DisLambdaTest=true -DisHeadLess=false -Denvname=dev -Dsuitexml.file=testsuites/RegressionTests.xml

    - name: Upload  Test logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: screenshot
        path: screenshot/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: html-report
        path: report.html
       
    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html  public/extent-reports/
        cp -R screenshot/ public/extent-reports/screenshot/
        ls -l

    - name: Deploy 🚀
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.GITHUBPAGE }}
        clean: true
